### Valid create user request 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test_three@example.com",
  "password": "test@123"
}

### Invalid create user request email missing
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "userId": "test@example.com",
  "password": "test@123"
}

### Invalid create user request password missing
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "userRole": "test@123"
}

### Invalid create user request email and password missing
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "userId": "test@example.com",
  "userRole": "test@123"
}

### Find by id
GET http://localhost:3000/auth/2


### Find by email id
GET http://localhost:3000/auth?email=test_one@example.com


### Remove user by id
DELETE http://localhost:3000/auth/4

### Update user by id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "newPassword123"
}


### Sign in user with valid user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test_three@example.com",
  "password": "test@123"
}


### Sign in user with invalid user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test_three@example.com",
  "password": "test@321"
}

### Who am i
GET http://localhost:3000/auth/whoami

### sign out
GET http://localhost:3000/auth/signout

